### ISSUE TITLE
Change submodules back to classes

### ISSUE THREAD

**Issue by juanep97** [IAA-CSIC/MUTIS#8]
I think Signal and Correlation should be classes of the module mutis, and not their own submodules, because:

- The classes are small, it should be enough for them to be on a separate files, but they are not big enough to justify separate modules (and they won't be in the near future, probably).
- The classes are really not independent. The Correlation class only makes sense with Signal.
- It complicates the name space, the import process and the usage:
    - With submodules we need to do separate imports, and use them like: mutis.signal.Signal(...)
    - With classes we can do an 'import mutis', and use them like: mutis.Signal(...)

**Comment by Bultako** [comment]
@jjjon 

I can understand this is a valid request at this stage of the development of the package, I think we could make this change now and refactor the file structure at a later moment if needed. I would still keep the classes in separate files `correlation.py` and `signal.py` at the root level. 


So at the end we could use `mutis` as below

```Python
import mutis
signal1 = mutis.Signal(times, signs, generation_method)
signal2 = mutis.Signal(times, signs, generation_method)
correlation = mutis.Correlation(signal1, signal2, correlation_method)
```

and also at the same time as it can be used now

```Python
from mutis.signal import Signal
from correlation import Correlation 
signal1 = Signal(times, signs, generation_method)
signal2 = Signal(times, signs, generation_method)
correlation = Correlation(signal1, signal2, correlation_method)
```

so we will not have to modify our notebooks and recipes working now..
is it ok with you?

**Comment by juanep97** [comment]
So the easiest solutions is adding:
```Python
from .correlation import Correlation
from .signal import Signal
```
to `mutis//__init__.py ` I think. If not you tell me. I send merge request.

**Comment by rlopezcoto** [comment]
I think that this is related to #2, if you do what you are proposing @jjjon, then every time you do `import mutis`, it will be loading the `correlation` and `signal` packages and as @Bultako suggested in  https://github.com/IAA-CSIC/MUTIS/pull/2#issuecomment-841110514, this may not be the way to go in case the package grows and you do not want to load all the functionalities when importing it

**Comment by Bultako** [comment]
I think at this stage this is mostly a matter of taste in the **tree folder structure of the package**, since I strongly advocate to keep the interface as it is now. Because it is simpler with less chars to type in the code if you consider the whole list of commands in the whole analysis process (shorter `s=Signal` than `s=mutis.Signal`), and also to not modify the [notebooks](https://iaa-csic.github.io/MUTIS/_build/html/recipes/mutis_workflow.html) we have already working. So, what I would suggest is do whatever solution you like as far as you keep the interface untouched, which is:

```Python
from mutis.signal import Signal
from correlation import Correlation 
signal1 = Signal(times, signs, generation_method)
signal2 = Signal(times, signs, generation_method)
correlation = Correlation(signal1, signal2, correlation_method)
```

What you propose is not the way how other bigger projects work (see [astropy](https://github.com/astropy/astropy), [sunpy](https://github.com/sunpy/sunpy), [gammapy](https://github.com/gammapy/gammapy), etc.), and I guess we will have to change the tree-folder structure if the code grows in complexity. But at this moment I am ok with having a simpler structure, which is `import mutis` and have everything in the `mutis` namespace. If you want to go in this way and also keep the interface access above, I would go in the direction of the tree-folder structure below..

```
mutis
├── __init__.py
├── correlation.py
├── signal.py
├── lib
│   ├── __init__.py
│   ├── correlation.py
│   └── signal.py
└── utils
    ├── __init__.py
    └── utils.py
``` 

which allows to import everything in the `mutis` namespace with `import mutis`, and at the same time keeps the present interface untouched. But before doing the PR I would have a look at three functional [notebooks](https://iaa-csic.github.io/MUTIS/_build/html/recipes/mutis_workflow.html) at the documentation and think carefully on what we gain and lose with this change.

**Comment by juanep97** [comment]
I think that's the best solution, if it mantains the current interface:
```Python
import mutis
...
sig = mutis.Signal(t, s, generation_method)
...
correlation = mutis.Correlation(sig1, sig2, correlation_method)
```
so we don't have to modify any notebook and also to make the usage clearer and easier. In any case if the package grows so much we need to have submodules, **Correlation and Signal will probably stay in the same submodule**, since Correlation only makes sense with signals. But my comment is only regarding the interface, so you tell me which way you think is the best to implement it having separate files. I sent a push request which added a few imports but if there's a better way...

**Comment by Bultako** [comment]
@jjjon 

If you follow the tree-structure I pasted in message above together with the filenames translation below, we could have both interfaces working with no submodules.

`correlation/core.py` -> `correlation.py` 
`signal/core.py` -> `signal.py`
`correlation/functions.py` -> `lib/correlation.py` 
`signal/functions.py` -> `lib/signal.py` 

You will also have to change the imports in the scripts and add the following in the `__init__.py` script at the root level.

```Python
from mutis.signal import Signal
from mutis.correlation import Correlation
```

**Comment by juanep97** [comment]
I think the file structure is right now. If you are ok I merge with main and start updating the code to the last version (pre-github).

**Comment by Bultako** [comment]
@jjjon 
just make a pull request with the changes you have made locally related to this issue.

**Comment by juanep97** [comment]
Ah OK, I had the branch but forgot to do the merge request, I think.
